# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c05eb5ed95b03103a6f2329f3821985256a32e85b353ed342b6970a6ed5efdebcb6d306a0df156a963a2ddfca2783e26100d00446a8b6ae493ad3f7b31e4c63

test:
  secret_key_base: 7e624a181301fdd74a46b545a886936869128072020f469631c822073bdcd4d9066c60288e410aa399776f9fb0a1ac5c072b05d699bfe875cff773ced8fb3eb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
